version: '3'

services:
  mysql-docker-service-1:
    container_name: srinivas-container
    image: mysql:latest
    ports:
      - 2012:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vasu
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
  ibm-mq-service:
    container_name: ibm-mq-container
    image: ibmcom/mq
    ports:
      - 1414:1414
      - 9443:9443
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
    volumes:
      - qm1data-7:/mnt/mqm
  spring-boot-hibernate-service-1:
    container_name: srinivas-container-2
    image: srinivas-image
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - mysql-docker-service-1
      - ibm-mq-service
    ports:
      - 8080:8080
volumes:
  qm1data-7:
